### ISSUE TITLE
0.3.0 pre-release checklist

### ISSUE THREAD

**Issue by YannickJadoul** [Jellevanderwerff/thebeat#101]
The very last issue to address before releasing 0.3.0!

- [ ] Remove Python 3.8 support in `pyproject.toml`, CI, etc.
- [ ] Add changelog entries
- [ ] _(to be extended, potentially)_
